In [8]:
from numpy import array

i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])

transform1 = array([i_hat1, j_hat1]).transpose()

print(i_hat1)
print(j_hat1)
print(transform1)

[0 1]
[-1  0]
[[ 0 -1]
 [ 1  0]]


In [12]:
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])

transform2 = array([i_hat2, j_hat2]).transpose()

print(i_hat2)
print(j_hat2)
print(transform2)

[1 0]
[1 1]
[[1 1]
 [0 1]]


In [13]:
combined = transform1 @ transform2
print(combined)

[[ 0 -1]
 [ 1  1]]


In [14]:
from numpy.linalg import det

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)
print(determinant)

6.0
