In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
all_data = pd.read_csv("light_set.csv")

In [5]:
all_data

,RED,GREEN,BLUE,LIGHT_OR_DARK_FONT_IND
0,0,0,0,1
1,0,0,128,1
2,0,0,139,1
3,0,0,205,1
4,0,0,238,1
...,...,...,...,...
1340,95,158,160,0
1341,96,123,139,1
1342,97,97,97,1
1343,99,184,255,0


In [6]:
all_data.iloc[1,:]

RED                         0
GREEN                       0
BLUE                      128
LIGHT_OR_DARK_FONT_IND      1
Name: 1, dtype: int64

In [9]:
all_data.iloc[1,0:3]

RED        0
GREEN      0
BLUE     128
Name: 1, dtype: int64

In [10]:
all_data.iloc[:,0:3].max()

RED      255
GREEN    255
BLUE     255
dtype: int64

In [11]:
all_data.iloc[:,0:3].min()

RED      0
GREEN    0
BLUE     0
dtype: int64

In [12]:
all_inputs = (all_data.iloc[:, 0:3].values / 255.0)

In [13]:
all_outputs = all_data.iloc[:,-1].values

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(all_inputs, all_outputs, test_size = 1/3)

In [15]:
X_train

array([[0.18039216, 0.18039216, 0.18039216],
       [0.93333333, 0.36078431, 0.25882353],
       [0.28235294, 0.4627451 , 1.        ],
       ...,
       [0.93333333, 0.91372549, 0.91372549],
       [0.41176471, 0.54509804, 0.41176471],
       [0.79215686, 0.88235294, 1.        ]], shape=(896, 3))

In [16]:
w_hidden = np.random.rand(3,3)

In [17]:
w_hidden

array([[0.15284348, 0.27949911, 0.87236871],
       [0.34674833, 0.3391936 , 0.40093875],
       [0.64131689, 0.53335289, 0.12202881]])

In [18]:
w_output = np.random.rand(1,3)

In [19]:
w_output

array([[0.93274435, 0.64859688, 0.13573034]])

In [21]:
b_hidden = np.random.rand(3, 1)

In [22]:
b_output = np.random.rand(1, 1)

In [24]:
relu = lambda x: np.maximum(x, 0)
logistic = lambda x: 1 / (1 + np.exp(-x))

In [25]:
def forward_prop(X) :
    Z1 = w_hidden @ X + b_hidden
    A1 = relu(Z1)
    Z2 = w_output @ A1 + b_output
    A2 = logistic(Z2)
    return Z1, A1, Z2, A2

In [33]:
test_predictions = forward_prop(X_train.transpose())[3]

In [34]:
test_comparisons = np.equal((test_predictions >= 0.5).flatten().astype(int), Y_train)

In [35]:
accuracy = sum(test_comparisons.astype(int) / X_train.shape[0])

In [36]:
accuracy

np.float64(0.37276785714285915)